import React from "react";
import { motion } from "framer-motion";
import { ArrowIcon } from "@/components/Icons";

import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import proFilePic from "../../public/profilePic.png";

const FramerImage = motion(Image);
const MotionLink = motion(Link);

const arrow = {
  initial: { translateX: 0 },
  animate: { translateX: -20 },
  transition: { duration: 1.4 },
};

const about = () => {
  return (
    <>
      <Head>
        <title>About Maurice</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <section className="pt-16 sm:pt-24 md:pt-32 mb-16 sm:mb-32 md:mb-56">
          <div className="w-full relative mx-auto px-4 sm:px-8 md:px-16 lg:px-32">
            <div className="w-full grid grid-cols-12 gap-4 sm:gap-6 md:gap-10 content-stretch justify-stretch justify-items-stretch items-stretch">
              <motion.p
                className="text-black font-light text-lg sm:text-xl md:text-2xl row-span-1 col-start-1 col-end-2 self-end"
                initial={{ y: -50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ delay: 1.2, duration: 1.4, ease: "easeOut" }}
              >
                01
              </motion.p>

              <div
                className="relative row-span-1 col-start-2 col-end-12 md:col-start-3 md:col-end-12 w-full flex flex-wrap items-center justify-start font-normal mx-auto text-[20vw] sm:text-[18vw] md:text-[16vw] text-black z-10 text-center uppercase"
                style={{ lineHeight: "91%", letterSpacing: "-0.5vw" }}
              >
                <div className="w-full flex flex-row justify-center items-center">
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.2, duration: 1.4, ease: "easeOut" }}
                  >
                    A
                  </motion.h1>
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.25, duration: 1.4, ease: "easeOut" }}
                  >
                    b
                  </motion.h1>
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.3, duration: 1.4, ease: "easeOut" }}
                  >
                    o
                  </motion.h1>
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.35, duration: 1.4, ease: "easeOut" }}
                  >
                    u
                  </motion.h1>
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.4, duration: 1.4, ease: "easeOut" }}
                  >
                    t
                  </motion.h1>
                </div>
              </div>

              <motion.p
                className="text-black text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-light row-span-2 col-start-1 col-end-12 md:col-start-4 md:col-end-13"
                initial={{ y: 50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ delay: 1.2, duration: 1.4, ease: "easeOut" }}
              >
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Suspendisse varius enim in eros elementum tristique.
              </motion.p>

              <motion.p
                className="mt-8 sm:mt-12 md:mt-24 text-black text-base sm:text-lg md:text-xl lg:text-2xl row-span-3 font-light col-start-1 col-end-12 md:col-start-7 md:col-end-13"
                initial={{ y: 50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ delay: 1.2, duration: 1.4, ease: "easeOut" }}
              >
                Nunc urna, montes, id purus eget. Vestibulum sit non diam purus.
                At nibh aenean eu venenatis id fames sollicitudin. Erat fusce
                commodo, velit cursus quis nibh arcu aliquet enim. Nunc urna,
                montes, id purus eget. Vestibulum sit non diam purus. At nibh
                aenean eu venenatis id fames sollicitudin. Erat fusce commodo,
                velit cursus quis nibh arcu aliquet enim.
              </motion.p>

              <div className="relative overflow-hidden row-span-3 col-start-1 col-end-12 md:col-start-2 md:col-end-6 mt-8 md:mt-0">
                <motion.div
                  initial={{ opacity: 0, scaleX: 1.5, scaleY: 1.5 }}
                  animate={{ opacity: 1, scaleX: 1, scaleY: 1 }}
                  transition={{ delay: 1.2, duration: 1.2, ease: "easeInOut" }}
                  className="w-full h-full"
                >
                  <FramerImage
                    priority
                    alt="profilePic"
                    style={{ objectFit: "cover" }}
                    src={proFilePic}
                  />
                </motion.div>
              </div>
            </div>
          </div>
        </section>

        <section className="mb-16 sm:mb-32 md:mb-56">
          <div className="w-full relative mx-auto px-4 sm:px-8 md:px-16 lg:px-32">
            <motion.div
              className="w-full grid grid-cols-12 mb-8 sm:mb-16 md:mb-28 content-stretch justify-stretch justify-items-stretch items-stretch"
              initial={{ y: 50, opacity: 0 }}
              whileInView={{ y: 0, opacity: 1 }}
              transition={{ duration: 1.4, ease: "easeOut" }}
            >
              <motion.p
                className="text-black font-light text-lg sm:text-xl md:text-2xl row-span-1 col-start-1 col-end-2 self-end"
                initial={{ y: -50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ duration: 1.4, ease: "easeOut" }}
              >
                02
              </motion.p>

              <h2
                className="text-black font-normal uppercase row-span-1 col-start-3 col-end-12 md:col-start-4 md:col-end-12 text-[18vw] sm:text-[14vw] md:text-[11vw] self-end justify-start"
                style={{ lineHeight: "89%" }}
              >
                Services
              </h2>
            </motion.div>

            <div className="w-full grid grid-cols-12 gap-x-4 sm:gap-x-6 md:gap-x-10">
              <div className="col-start-1 col-end-12 md:col-start-4 md:col-end-13">
                <motion.div
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  animate="initial"
                  whileHover="animate"
                  transition={{ duration: 1.4, ease: "easeOut" }}
                >
                  <MotionLink
                    href="/"
                    className="flex flex-col py-12 pb-16 border-y-[1px] border-lightGrey"
                  >
                    <div className="flex flex-row pl-0 md:pl-56 pb-6 sm:pb-8 md:pb-12 items-center gap-4">
                      <p className="w-full text-black row-span-1 col-span-2 text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-light">
                        Strategy
                      </p>
                      <motion.div
                        variants={arrow}
                        className="flex items-center justify-center p-2 sm:p-3 rounded-full bg-black gap-4 flex-shrink-0"
                      >
                        <ArrowIcon
                          className="w-8 h-8 sm:w-10 sm:h-10 md:w-12 md:h-12 -rotate-[135deg]"
                          color={"white"}
                        />
                      </motion.div>
                    </div>

                    <div className="flex flex-col sm:flex-row gap-2 sm:gap-0">
                      <p className="text-black font-light text-lg sm:text-xl md:text-2xl col-start-1 col-end-1 row-span-2 self-end">
                        01
                      </p>
                      <p className="pl-0 sm:pl-8 md:pl-[12.5rem] text-black font-light text-base sm:text-lg md:text-xl lg:text-2xl col-start-2 row-span-2">
                        Ac viverra purus in in pretium arcu amet. Morbi nisl
                        mauris sagittis purus donec.
                      </p>
                    </div>
                  </MotionLink>
                </motion.div>
              </div>

              <div className="col-start-4 col-end-13">
                <motion.div
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  animate="initial"
                  whileHover="animate"
                  transition={{ delay: 0.2, duration: 1.4, ease: "easeOut" }}
                >
                  <MotionLink
                    href="/"
                    className="flex flex-col py-12 pb-16 border-b-[1px] border-lightGrey"
                  >
                    <div className="flex flex-row pl-56 pb-12 items-center">
                      <p className="w-full text-black row-span-1 col-span-2 text-5xl font-light">
                        Brand design
                      </p>
                      <motion.div
                        className="flex items-center justify-center p-3 rounded-full bg-black gap-4"
                        variants={arrow}
                      >
                        <ArrowIcon
                          className="w-12 h-12 -rotate-[135deg]"
                          color={"white"}
                        />
                      </motion.div>
                    </div>

                    <div className="flex flex-row">
                      <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                        02
                      </p>
                      <p className="pl-[12.5rem] text-black font-light text-2xl col-start-2 row-span-2">
                        Ac viverra purus in in pretium arcu amet. Morbi nisl
                        mauris sagittis purus donec.
                      </p>
                    </div>
                  </MotionLink>
                </motion.div>
              </div>

              <div className="col-start-4 col-end-13">
                <motion.div
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  animate="initial"
                  whileHover="animate"
                  transition={{ delay: 0.2, duration: 1.4, ease: "easeOut" }}
                >
                  <MotionLink
                    href="/"
                    className="flex flex-col py-12 pb-16 border-b-[1px] border-lightGrey"
                  >
                    <div className="flex flex-row pl-56 pb-12 items-center">
                      <p className="w-full text-black row-span-1 col-span-2 text-5xl font-light">
                        Web design
                      </p>
                      <motion.div
                        className="flex items-center justify-center p-3 rounded-full bg-black gap-4"
                        variants={arrow}
                      >
                        <ArrowIcon
                          className="w-12 h-12 -rotate-[135deg]"
                          color={"white"}
                        />
                      </motion.div>
                    </div>

                    <div className="flex flex-row">
                      <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                        03
                      </p>
                      <p className="pl-[12.5rem] text-black font-light text-2xl col-start-2 row-span-2">
                        Ac viverra purus in in pretium arcu amet. Morbi nisl
                        mauris sagittis purus donec.
                      </p>
                    </div>
                  </MotionLink>
                </motion.div>
              </div>
            </div>
          </div>
        </section>

        <section className="mb-16 sm:mb-32 md:mb-56">
          <div className="w-full relative mx-auto px-4 sm:px-8 md:px-16 lg:px-32">
            <motion.div
              className="w-full grid grid-cols-12 gap-4 sm:gap-6 md:gap-10 mb-8 sm:mb-16 md:mb-28 content-stretch justify-stretch justify-items-stretch items-stretch"
              initial={{ y: 50 }}
              whileInView={{ y: 0 }}
              transition={{ duration: 1.4, ease: "easeOut" }}
            >
              <motion.p
                className="text-black font-light text-lg sm:text-xl md:text-2xl row-span-1 col-start-1 col-end-2 self-end"
                initial={{ y: -50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ duration: 1.4, ease: "easeOut" }}
              >
                03
              </motion.p>

              <h2
                className="text-black font-normal uppercase row-span-1 col-start-3 col-end-12 md:col-start-4 md:col-end-12 text-[18vw] sm:text-[14vw] md:text-[11vw] self-end justify-start"
                style={{ lineHeight: "85%" }}
              >
                Process
              </h2>

              <motion.p
                className="text-black text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-light row-span-2 col-start-1 col-end-12 md:col-start-4 md:col-end-13"
                initial={{ y: 50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ duration: 1.4, ease: "easeOut" }}
              >
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Suspendisse varius enim in eros elementum tristique.
              </motion.p>
            </motion.div>

            <div className="w-full grid grid-cols-12 gap-y-8 sm:gap-y-12 md:gap-y-24 content-stretch justify-stretch justify-items-stretch items-stretch">
              <motion.div
                className="col-start-1 col-end-12 md:col-start-2 md:col-end-6"
                initial={{ y: 50 }}
                whileInView={{ y: 0 }}
                transition={{ duration: 1.4, ease: "easeOut" }}
              >
                <p className="text-black text-2xl sm:text-3xl md:text-4xl font-light mb-8 sm:mb-12 md:mb-16">
                  Research
                </p>
                <p className="text-black text-base sm:text-lg md:text-xl lg:text-2xl font-light">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Suspendisse varius enim in eros elementum tristique. Duis
                  cursus, mi quis viverra ornare, eros dolor interdum nulla, ut
                  commodo diam libero vitae erat.
                </p>
              </motion.div>

              <motion.div
                className="col-start-1 col-end-12 md:col-start-8 md:col-end-12"
                initial={{ y: 50 }}
                whileInView={{ y: 0 }}
                transition={{ duration: 1.4, ease: "easeOut" }}
              >
                <p className="text-black text-2xl sm:text-3xl md:text-4xl font-light mb-8 sm:mb-12 md:mb-16">
                  Strategy
                </p>
                <p className="text-black text-base sm:text-lg md:text-xl lg:text-2xl font-light">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Suspendisse varius enim in eros elementum tristique. Duis
                  cursus, mi quis viverra ornare, eros dolor interdum nulla, ut
                  commodo diam libero vitae erat.
                </p>
              </motion.div>

              <motion.div
                className="col-start-1 col-end-12 md:col-start-2 md:col-end-6"
                initial={{ y: 50 }}
                whileInView={{ y: 0 }}
                transition={{ duration: 1.4, ease: "easeOut" }}
              >
                <p className="text-black text-2xl sm:text-3xl md:text-4xl font-light mb-8 sm:mb-12 md:mb-16">
                  Execution
                </p>
                <p className="text-black text-base sm:text-lg md:text-xl lg:text-2xl font-light">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Suspendisse varius enim in eros elementum tristique. Duis
                  cursus, mi quis viverra ornare, eros dolor interdum nulla, ut
                  commodo diam libero vitae erat.
                </p>
              </motion.div>

              <motion.div
                className="col-start-1 col-end-12 md:col-start-8 md:col-end-12"
                initial={{ y: 50 }}
                whileInView={{ y: 0 }}
                transition={{ duration: 1.4, ease: "easeOut" }}
              >
                <p className="text-black text-2xl sm:text-3xl md:text-4xl font-light mb-8 sm:mb-12 md:mb-16">
                  Evaluation
                </p>
                <p className="text-black text-base sm:text-lg md:text-xl lg:text-2xl font-light">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Suspendisse varius enim in eros elementum tristique. Duis
                  cursus, mi quis viverra ornare, eros dolor interdum nulla, ut
                  commodo diam libero vitae erat.
                </p>
              </motion.div>
            </div>
          </div>
        </section>

        <section className="mb-16 sm:mb-32 md:mb-56">
          <div className="w-full relative mx-auto px-4 sm:px-8 md:px-16 lg:px-32">
            <motion.div
              className="w-full grid grid-cols-12 mb-8 sm:mb-16 md:mb-28 content-stretch justify-stretch justify-items-stretch items-stretch"
              initial={{ y: 50 }}
              whileInView={{ y: 0 }}
              transition={{ duration: 1.4, ease: "easeOut" }}
            >
              <p
                className="text-black font-light text-lg sm:text-xl md:text-2xl row-span-1 col-start-1 col-end-2 self-end"
                initial={{ y: -50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ duration: 1.4, ease: "easeOut" }}
              >
                02
              </p>

              <h2
                className="text-black uppercase row-span-1 col-start-3 col-end-12 md:col-start-4 md:col-end-12 text-[18vw] sm:text-[14vw] md:text-[11vw] self-end justify-start"
                style={{ lineHeight: "89%" }}
              >
                Mentions
              </h2>
            </motion.div>

            <div className="w-full grid grid-cols-12 gap-x-4 sm:gap-x-6 md:gap-x-10">
              <div className="col-start-1 col-end-12 md:col-start-4 md:col-end-13">
                <motion.div
                  className="flex flex-col sm:flex-row py-4 border-y-[1px] justify-between border-lightGrey gap-2 sm:gap-0"
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  transition={{ duration: 1.4, ease: "easeOut" }}
                >
                  <p className="text-black font-light text-base sm:text-lg md:text-xl lg:text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Varius enim in eros
                  </p>
                  <p className="text-black font-light text-base sm:text-lg md:text-xl lg:text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Aenean Magazine
                  </p>
                  <p className="text-black font-light text-base sm:text-lg md:text-xl lg:text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    2023
                  </p>
                </motion.div>

                <motion.div
                  className="flex flex-row py-4 border-b-[1px] justify-between border-lightGrey"
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  transition={{ duration: 1.4, ease: "easeOut" }}
                >
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Varius enim in eros
                  </p>
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Aenean Magazine
                  </p>
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    2023
                  </p>
                </motion.div>

                <motion.div
                  className="flex flex-row py-4 border-b-[1px] justify-between border-lightGrey"
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  transition={{ duration: 1.4, ease: "easeOut" }}
                >
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Varius enim in eros
                  </p>
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Aenean Magazine
                  </p>
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    2023
                  </p>
                </motion.div>

                <motion.div
                  className="flex flex-row py-4 border-b-[1px] justify-between border-lightGrey"
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  transition={{ duration: 1.4, ease: "easeOut" }}
                >
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Varius enim in eros
                  </p>
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Aenean Magazine
                  </p>
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    2023
                  </p>
                </motion.div>

                <motion.div
                  className="flex flex-row py-4 border-b-[1px] justify-between border-lightGrey"
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  transition={{ duration: 1.4, ease: "easeOut" }}
                >
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Varius enim in eros
                  </p>
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Aenean Magazine
                  </p>
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    2023
                  </p>
                </motion.div>

                <motion.div
                  className="flex flex-row py-4 border-b-[1px] justify-between border-lightGrey"
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  transition={{ duration: 1.4, ease: "easeOut" }}
                >
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Varius enim in eros
                  </p>
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    Aenean Magazine
                  </p>
                  <p className="text-black font-light text-2xl col-start-1 col-end-1 row-span-2 self-end">
                    2023
                  </p>
                </motion.div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default about;
