import React from "react";
import { motion } from "framer-motion";

import Head from "next/head";
import Link from "next/link";
import { ArrowIcon } from "@/components/Icons";
const MotionLink = motion(Link);

const arrow = {
  initial: { translateX: 0 },
  animate: { translateX: -20 },
  transition: { duration: 1.4 },
};

const contact = () => {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <section className="pt-16 sm:pt-24 md:pt-32 mb-16 sm:mb-32 md:mb-56">
          <div className="w-full relative mx-auto px-4 sm:px-8 md:px-16 lg:px-28">
            <div className="w-full grid grid-cols-12 gap-4 sm:gap-6 md:gap-10 mb-8 sm:mb-16 md:mb-28 content-stretch justify-stretch justify-items-stretch items-stretch">
              <motion.p
                className="text-black font-light text-lg sm:text-xl md:text-2xl row-span-1 col-start-1 col-end-2 self-end"
                initial={{ y: -50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ delay: 1.2, duration: 1.4, ease: "easeOut" }}
              >
                01
              </motion.p>

              <div
                className="relative row-span-1 col-start-2 col-end-12 md:col-start-4 md:col-end-12 w-full flex flex-wrap items-center justify-center font-normal mx-auto text-[20vw] sm:text-[18vw] md:text-[16vw] text-black z-10 text-center uppercase"
                style={{ lineHeight: "91%", letterSpacing: "-0.5vw" }}
              >
                <div className="w-full flex flex-row justify-start items-center md:-ml-12">
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.2, duration: 1.4, ease: "easeOut" }}
                  >
                    H
                  </motion.h1>
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.25, duration: 1.4, ease: "easeOut" }}
                  >
                    i
                  </motion.h1>
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.3, duration: 1.4, ease: "easeOut" }}
                  >
                    t
                  </motion.h1>

                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.4, duration: 1.4, ease: "easeOut" }}
                    className="ml-14"
                  >
                    M
                  </motion.h1>
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.45, duration: 1.4, ease: "easeOut" }}
                  >
                    e
                  </motion.h1>
                </div>
              </div>

              <motion.p
                className="text-black text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-light row-span-2 col-start-1 col-end-12 md:col-start-4 md:col-end-12"
                initial={{ y: 50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ delay: 1.2, duration: 1.4, ease: "easeOut" }}
              >
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Suspendisse varius enim in eros elementum tristique.
              </motion.p>

              <div className="row-span-3 col-start-1 col-end-12 md:col-start-4 md:col-end-13 pt-8 sm:pt-12 md:pt-20">
                <input
                  placeholder="Your name"
                  className="w-full bg-light border-b-[1px] border-lightGrey text-base sm:text-lg font-normal text-black pt-3 pb-6 sm:pb-8 mb-8 sm:mb-12 focus:outline-none"
                />

                <input
                  placeholder="Your email"
                  type="email"
                  className="w-full bg-light border-b-[1px] border-lightGrey text-base sm:text-lg font-normal text-black pt-3 pb-6 sm:pb-8 mb-8 sm:mb-12 focus:outline-none"
                />

                <textarea
                  rows="4"
                  placeholder="Your message"
                  className="w-full min-h-[120px] sm:min-h-[150px] md:min-h-[180px] bg-light border-b-[1px] border-lightGrey text-base sm:text-lg font-normal text-black pt-3 pb-6 sm:pb-8 mb-8 sm:mb-12 focus:outline-none"
                />

                <button className="text-lg sm:text-xl text-black font-normal border-b-[1px] border-lightGrey pb-2">
                  Submit you message
                </button>
              </div>
            </div>
          </div>
        </section>

        <section className="mb-16 sm:mb-32 md:mb-56">
          <div className="w-full relative mx-auto px-4 sm:px-8 md:px-16 lg:px-28">
            <motion.div
              className="w-full grid grid-cols-12 mb-8 sm:mb-16 md:mb-28 content-stretch justify-stretch justify-items-stretch items-stretch"
              initial={{ y: 50, opacity: 0 }}
              whileInView={{ y: 0, opacity: 1 }}
              transition={{ duration: 1.4, ease: "easeOut" }}
            >
              <motion.p
                className="text-black font-light text-lg sm:text-xl md:text-2xl row-span-1 col-start-1 col-end-2 self-end"
                initial={{ y: -50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ duration: 1.4, ease: "easeOut" }}
              >
                02
              </motion.p>

              <h2
                className="text-black font-normal uppercase row-span-1 col-start-3 col-end-12 md:col-start-4 md:col-end-12 text-[18vw] sm:text-[14vw] md:text-[11vw] self-end justify-start"
                style={{ lineHeight: "89%" }}
              >
                Socials
              </h2>
            </motion.div>

            <div className="w-full grid grid-cols-12 gap-x-4 sm:gap-x-6 md:gap-x-10">
              <div className="col-start-1 col-end-12 md:col-start-4 md:col-end-13">
                <motion.div
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  animate="initial"
                  whileHover="animate"
                  transition={{ duration: 1.4, ease: "easeOut" }}
                >
                  <MotionLink
                    href="/"
                    className="flex flex-row items-center py-6 sm:py-8 md:py-12 border-y-[1px] justify-between border-lightGrey"
                  >
                    <p className="text-black font-light text-2xl sm:text-3xl md:text-4xl lg:text-5xl col-start-1 col-end-1 row-span-2">
                      Instagram
                    </p>
                    <motion.div
                      variants={arrow}
                      className="flex items-center justify-center p-2 sm:p-3 rounded-full bg-black gap-4 flex-shrink-0"
                    >
                      <ArrowIcon
                        className="w-8 h-8 sm:w-10 sm:h-10 md:w-12 md:h-12 -rotate-[135deg]"
                        color={"white"}
                      />
                    </motion.div>
                  </MotionLink>
                </motion.div>

                <motion.div
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  animate="initial"
                  whileHover="animate"
                  transition={{ duration: 1.4, ease: "easeOut" }}
                >
                  <MotionLink
                    href="/"
                    className="flex flex-row items-center py-6 sm:py-8 md:py-12 border-b-[1px] justify-between border-lightGrey"
                  >
                    <p className="text-black font-light text-2xl sm:text-3xl md:text-4xl lg:text-5xl col-start-1 col-end-1 row-span-2">
                      Facebook
                    </p>
                    <motion.div
                      variants={arrow}
                      className="flex items-center justify-center p-2 sm:p-3 rounded-full bg-black gap-4"
                    >
                      <ArrowIcon
                        className="w-8 h-8 sm:w-10 sm:h-10 md:w-12 md:h-12 -rotate-[135deg]"
                        color={"white"}
                      />
                    </motion.div>
                  </MotionLink>
                </motion.div>

                <motion.div
                  initial={{ y: 50 }}
                  whileInView={{ y: 0 }}
                  animate="initial"
                  whileHover="animate"
                  transition={{ duration: 1.4, ease: "easeOut" }}
                >
                  <MotionLink
                    href="/"
                    className="flex flex-row items-center py-6 sm:py-8 md:py-12 border-b-[1px] justify-between border-lightGrey"
                  >
                    <p className="text-black font-light text-2xl sm:text-3xl md:text-4xl lg:text-5xl col-start-1 col-end-1 row-span-2">
                      Linkedin
                    </p>
                    <motion.div
                      variants={arrow}
                      className="flex items-center justify-center p-2 sm:p-3 rounded-full bg-black gap-4"
                    >
                      <ArrowIcon
                        className="w-8 h-8 sm:w-10 sm:h-10 md:w-12 md:h-12 -rotate-[135deg]"
                        color={"white"}
                      />
                    </motion.div>
                  </MotionLink>
                </motion.div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default contact;
