import React from "react";
import { motion } from "framer-motion";

import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Faune from "../../public/images/Faune.png";
import LeBuzz from "../../public/images/LeBuzz.jpeg";
import AlmaBrava from "../../public/images/AlmaBrava.png";
import WaterJournal from "../../public/images/WaterJournal.png";

const MotionLink = motion(Link);

const work = () => {
  return (
    <>
      <Head>
        <title>Work Maurice</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <section className="pt-32">
          <div className="w-full relative mx-auto px-28">
            <div className="w-full grid grid-cols-12 gap-10 mb-28 content-stretch justify-stretch justify-items-stretch items-stretch">
              <motion.p
                className="text-black font-light text-2xl row-span-1 col-start-1 col-end-2 self-end"
                initial={{ y: -50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ delay: 1.2, duration: 1.4, ease: "easeOut" }}
              >
                01
              </motion.p>

              <div
                className="relative row-span-1 col-start-4 col-end-12 w-full flex flex-wrap items-center justify-center font-normal mx-auto text-[16vw] text-black z-10 text-center uppercase"
                style={{ lineHeight: "91%", letterSpacing: "-0.5vw" }}
              >
                <div className="w-full flex flex-row justify-start items-center">
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.2, duration: 1.4, ease: "easeOut" }}
                  >
                    W
                  </motion.h1>
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.25, duration: 1.4, ease: "easeOut" }}
                  >
                    o
                  </motion.h1>
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.3, duration: 1.4, ease: "easeOut" }}
                  >
                    r
                  </motion.h1>
                  <motion.h1
                    initial={{ opacity: 0, rotateZ: 5, translateY: "100%" }}
                    animate={{ translateY: 0, rotateZ: 0, opacity: 1 }}
                    transition={{ delay: 0.35, duration: 1.4, ease: "easeOut" }}
                  >
                    k
                  </motion.h1>
                </div>
              </div>

              <motion.p
                className="text-black text-5xl font-light row-span-2 col-start-4 col-end-13"
                initial={{ y: 50, opacity: 0 }}
                whileInView={{ y: 0, opacity: 1 }}
                transition={{ delay: 1.2, duration: 1.4, ease: "easeOut" }}
              >
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Suspendisse varius enim in eros elementum tristique.
              </motion.p>
            </div>
          </div>
        </section>

        <section className="mb-64">
          <div className="relative !mx-auto px-28">
            <div className="grid grid-cols-12 gap-20">
              <div className="flex col-start-1 col-end-12 items-center justify-center relative overflow-hidden">
                <MotionLink
                  href="/"
                  initial={{ scale: 1.25 }}
                  whileInView={{ scale: 1 }}
                  transition={{ delay: 0.5, duration: 1.4, ease: "easeOut" }}
                  className="w-full h-full"
                >
                  <div className="w-full h-full absolute z-10 top-auto bottom-auto left-auto right-auto bg-black opacity-20" />
                  <Image
                    alt="WaterJournal"
                    src={WaterJournal}
                    className="w-full"
                  />
                  <motion.div
                    className="absolute z-20 top-auto bottom-12 left-12 right-12 flex items-stretch justify-between"
                    initial={{ y: 50, opacity: 0 }}
                    whileInView={{ y: 0, opacity: 1 }}
                    transition={{ duration: 1.4, ease: "easeOut" }}
                  >
                    <h3 className="uppercase text-3xl text-white">
                      Water Journal
                    </h3>
                    <p className="text-2xl text-white font-light">
                      Brand Strategy
                    </p>
                  </motion.div>
                </MotionLink>
              </div>

              <div className="flex col-start-1 col-end-12 items-center justify-center relative overflow-hidden">
                <MotionLink
                  href="/"
                  initial={{ scale: 1.25 }}
                  whileInView={{ scale: 1 }}
                  transition={{ delay: 0.5, duration: 1.4, ease: "easeOut" }}
                  className="w-full h-full"
                >
                  <div className="w-full h-full absolute z-10 top-auto bottom-auto left-auto right-auto bg-black opacity-20" />
                  <Image alt="Faune" src={Faune} className="w-full" />
                  <motion.div
                    className="absolute z-20 top-auto bottom-12 left-12 right-12 flex items-stretch justify-between"
                    initial={{ y: 50, opacity: 0 }}
                    whileInView={{ y: 0, opacity: 1 }}
                    transition={{ duration: 1.4, ease: "easeOut" }}
                  >
                    <h3 className="uppercase text-3xl text-white">Faune</h3>
                    <p className="text-2xl text-white font-light">
                      Brand design
                    </p>
                  </motion.div>
                </MotionLink>
              </div>

              <div className="flex col-start-1 col-end-12 items-center justify-center relative overflow-hidden">
                <MotionLink
                  href="/"
                  initial={{ scale: 1.25 }}
                  whileInView={{ scale: 1 }}
                  transition={{ delay: 0.5, duration: 1.4, ease: "easeOut" }}
                  className="w-full h-full"
                >
                  <div className="w-full h-full absolute z-10 top-auto bottom-auto left-auto right-auto bg-black opacity-20" />
                  <Image alt="AlmaBrava" src={AlmaBrava} className="w-full" />
                  <motion.div
                    className="absolute z-20 top-auto bottom-12 left-12 right-12 flex items-stretch justify-between"
                    initial={{ y: 50, opacity: 0 }}
                    whileInView={{ y: 0, opacity: 1 }}
                    transition={{ duration: 1.4, ease: "easeOut" }}
                  >
                    <h3 className="uppercase text-3xl text-white">
                      Alma Brava
                    </h3>
                    <p className="text-2xl text-white font-light">
                      Brand design
                    </p>
                  </motion.div>
                </MotionLink>
              </div>

              <div className="flex col-start-1 col-end-13 items-center justify-center relative overflow-hidden">
                <MotionLink
                  href="/"
                  initial={{ scale: 1.25 }}
                  whileInView={{ scale: 1 }}
                  transition={{ delay: 0.5, duration: 1.4, ease: "easeOut" }}
                  className="w-full h-full"
                >
                  <div className="w-full h-full absolute z-10 top-auto bottom-auto left-auto right-auto bg-black opacity-20" />
                  <Image alt="LeBuzz" src={LeBuzz} className="w-full" />
                  <motion.div
                    className="absolute z-20 top-auto bottom-12 left-12 right-12 flex items-stretch justify-between"
                    initial={{ y: 50, opacity: 0 }}
                    whileInView={{ y: 0, opacity: 1 }}
                    transition={{ duration: 1.4, ease: "easeOut" }}
                  >
                    <h3 className="uppercase text-3xl text-white">Le Buzz</h3>
                    <p className="text-2xl text-white font-light">Web design</p>
                  </motion.div>
                </MotionLink>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default work;
