import React from "react";
import Head from "next/head";

const work = () => {
  return (
    <>
      <Head>
        <title>Work Maurice</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main></main>
    </>
  );
};

export default work;
